// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseCommon.proto

package com.fsgame.proto;

public final class MSGBaseCommon {
  private MSGBaseCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *登录状态
   * </pre>
   *
   * Protobuf enum {@code Pro.LoginState}
   */
  public enum LoginState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *登录失败
     * </pre>
     *
     * <code>_FAILD_ = 0;</code>
     */
    _FAILD_(0),
    /**
     * <code>_SUCESSED_ = 1;</code>
     */
    _SUCESSED_(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *登录失败
     * </pre>
     *
     * <code>_FAILD_ = 0;</code>
     */
    public static final int _FAILD__VALUE = 0;
    /**
     * <code>_SUCESSED_ = 1;</code>
     */
    public static final int _SUCESSED__VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LoginState valueOf(int value) {
      return forNumber(value);
    }

    public static LoginState forNumber(int value) {
      switch (value) {
        case 0: return _FAILD_;
        case 1: return _SUCESSED_;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoginState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginState>() {
            public LoginState findValueByNumber(int number) {
              return LoginState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fsgame.proto.MSGBaseCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoginState[] VALUES = values();

    public static LoginState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LoginState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pro.LoginState)
  }

  /**
   * <pre>
   *移动类型
   * </pre>
   *
   * Protobuf enum {@code Pro.MoveType}
   */
  public enum MoveType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>_RUN_ = 0;</code>
     */
    _RUN_(0),
    /**
     * <code>_WALK_ = 1;</code>
     */
    _WALK_(1),
    /**
     * <code>_SHOORT_ = 2;</code>
     */
    _SHOORT_(2),
    /**
     * <code>_SKILL_ = 3;</code>
     */
    _SKILL_(3),
    /**
     * <code>_JUMP_ = 4;</code>
     */
    _JUMP_(4),
    /**
     * <code>_STOPJUMP_ = 5;</code>
     */
    _STOPJUMP_(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>_RUN_ = 0;</code>
     */
    public static final int _RUN__VALUE = 0;
    /**
     * <code>_WALK_ = 1;</code>
     */
    public static final int _WALK__VALUE = 1;
    /**
     * <code>_SHOORT_ = 2;</code>
     */
    public static final int _SHOORT__VALUE = 2;
    /**
     * <code>_SKILL_ = 3;</code>
     */
    public static final int _SKILL__VALUE = 3;
    /**
     * <code>_JUMP_ = 4;</code>
     */
    public static final int _JUMP__VALUE = 4;
    /**
     * <code>_STOPJUMP_ = 5;</code>
     */
    public static final int _STOPJUMP__VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MoveType valueOf(int value) {
      return forNumber(value);
    }

    public static MoveType forNumber(int value) {
      switch (value) {
        case 0: return _RUN_;
        case 1: return _WALK_;
        case 2: return _SHOORT_;
        case 3: return _SKILL_;
        case 4: return _JUMP_;
        case 5: return _STOPJUMP_;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MoveType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MoveType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MoveType>() {
            public MoveType findValueByNumber(int number) {
              return MoveType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fsgame.proto.MSGBaseCommon.getDescriptor().getEnumTypes().get(1);
    }

    private static final MoveType[] VALUES = values();

    public static MoveType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MoveType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pro.MoveType)
  }

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * Protobuf enum {@code Pro.ChatType}
   */
  public enum ChatType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>_PLAYERCHAT_ = 0;</code>
     */
    _PLAYERCHAT_(0),
    /**
     * <pre>
     *系统推送信息
     * </pre>
     *
     * <code>_SYSTEMCHAT_ = 1;</code>
     */
    _SYSTEMCHAT_(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *玩家信息
     * </pre>
     *
     * <code>_PLAYERCHAT_ = 0;</code>
     */
    public static final int _PLAYERCHAT__VALUE = 0;
    /**
     * <pre>
     *系统推送信息
     * </pre>
     *
     * <code>_SYSTEMCHAT_ = 1;</code>
     */
    public static final int _SYSTEMCHAT__VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatType valueOf(int value) {
      return forNumber(value);
    }

    public static ChatType forNumber(int value) {
      switch (value) {
        case 0: return _PLAYERCHAT_;
        case 1: return _SYSTEMCHAT_;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
            public ChatType findValueByNumber(int number) {
              return ChatType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fsgame.proto.MSGBaseCommon.getDescriptor().getEnumTypes().get(2);
    }

    private static final ChatType[] VALUES = values();

    public static ChatType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pro.ChatType)
  }

  /**
   * <pre>
   *技能类型  暂时只有射击和魔法
   * </pre>
   *
   * Protobuf enum {@code Pro.SkillType}
   */
  public enum SkillType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>_SHOORTER_ = 0;</code>
     */
    _SHOORTER_(0),
    /**
     * <code>_MOFA_ = 1;</code>
     */
    _MOFA_(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>_SHOORTER_ = 0;</code>
     */
    public static final int _SHOORTER__VALUE = 0;
    /**
     * <code>_MOFA_ = 1;</code>
     */
    public static final int _MOFA__VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SkillType valueOf(int value) {
      return forNumber(value);
    }

    public static SkillType forNumber(int value) {
      switch (value) {
        case 0: return _SHOORTER_;
        case 1: return _MOFA_;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SkillType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SkillType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SkillType>() {
            public SkillType findValueByNumber(int number) {
              return SkillType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fsgame.proto.MSGBaseCommon.getDescriptor().getEnumTypes().get(3);
    }

    private static final SkillType[] VALUES = values();

    public static SkillType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SkillType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Pro.SkillType)
  }

  public interface CoordinateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.Coordinate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *x
     * </pre>
     *
     * <code>optional float x = 1;</code>
     */
    float getX();

    /**
     * <pre>
     *y
     * </pre>
     *
     * <code>optional float y = 2;</code>
     */
    float getY();

    /**
     * <pre>
     *z
     * </pre>
     *
     * <code>optional float z = 3;</code>
     */
    float getZ();

    /**
     * <pre>
     *朝向
     * </pre>
     *
     * <code>optional float o = 4;</code>
     */
    float getO();

    /**
     * <pre>
     *地图id
     * </pre>
     *
     * <code>optional int32 map = 5;</code>
     */
    int getMap();
  }
  /**
   * <pre>
   *玩家坐标信息
   * </pre>
   *
   * Protobuf type {@code Pro.Coordinate}
   */
  public  static final class Coordinate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.Coordinate)
      CoordinateOrBuilder {
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Coordinate() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
      o_ = 0F;
      map_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Coordinate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            case 37: {

              o_ = input.readFloat();
              break;
            }
            case 40: {

              map_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGBaseCommon.internal_static_Pro_Coordinate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGBaseCommon.internal_static_Pro_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGBaseCommon.Coordinate.class, com.fsgame.proto.MSGBaseCommon.Coordinate.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <pre>
     *x
     * </pre>
     *
     * <code>optional float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <pre>
     *y
     * </pre>
     *
     * <code>optional float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <pre>
     *z
     * </pre>
     *
     * <code>optional float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int O_FIELD_NUMBER = 4;
    private float o_;
    /**
     * <pre>
     *朝向
     * </pre>
     *
     * <code>optional float o = 4;</code>
     */
    public float getO() {
      return o_;
    }

    public static final int MAP_FIELD_NUMBER = 5;
    private int map_;
    /**
     * <pre>
     *地图id
     * </pre>
     *
     * <code>optional int32 map = 5;</code>
     */
    public int getMap() {
      return map_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      if (o_ != 0F) {
        output.writeFloat(4, o_);
      }
      if (map_ != 0) {
        output.writeInt32(5, map_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (o_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, o_);
      }
      if (map_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, map_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGBaseCommon.Coordinate)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGBaseCommon.Coordinate other = (com.fsgame.proto.MSGBaseCommon.Coordinate) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && (
          java.lang.Float.floatToIntBits(getO())
          == java.lang.Float.floatToIntBits(
              other.getO()));
      result = result && (getMap()
          == other.getMap());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + O_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getO());
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + getMap();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGBaseCommon.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGBaseCommon.Coordinate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩家坐标信息
     * </pre>
     *
     * Protobuf type {@code Pro.Coordinate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.Coordinate)
        com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGBaseCommon.internal_static_Pro_Coordinate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGBaseCommon.internal_static_Pro_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGBaseCommon.Coordinate.class, com.fsgame.proto.MSGBaseCommon.Coordinate.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGBaseCommon.Coordinate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        o_ = 0F;

        map_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGBaseCommon.internal_static_Pro_Coordinate_descriptor;
      }

      public com.fsgame.proto.MSGBaseCommon.Coordinate getDefaultInstanceForType() {
        return com.fsgame.proto.MSGBaseCommon.Coordinate.getDefaultInstance();
      }

      public com.fsgame.proto.MSGBaseCommon.Coordinate build() {
        com.fsgame.proto.MSGBaseCommon.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGBaseCommon.Coordinate buildPartial() {
        com.fsgame.proto.MSGBaseCommon.Coordinate result = new com.fsgame.proto.MSGBaseCommon.Coordinate(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.o_ = o_;
        result.map_ = map_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGBaseCommon.Coordinate) {
          return mergeFrom((com.fsgame.proto.MSGBaseCommon.Coordinate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGBaseCommon.Coordinate other) {
        if (other == com.fsgame.proto.MSGBaseCommon.Coordinate.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getO() != 0F) {
          setO(other.getO());
        }
        if (other.getMap() != 0) {
          setMap(other.getMap());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGBaseCommon.Coordinate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGBaseCommon.Coordinate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <pre>
       *x
       * </pre>
       *
       * <code>optional float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <pre>
       *x
       * </pre>
       *
       * <code>optional float x = 1;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *x
       * </pre>
       *
       * <code>optional float x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <pre>
       *y
       * </pre>
       *
       * <code>optional float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <pre>
       *y
       * </pre>
       *
       * <code>optional float y = 2;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *y
       * </pre>
       *
       * <code>optional float y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <pre>
       *z
       * </pre>
       *
       * <code>optional float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <pre>
       *z
       * </pre>
       *
       * <code>optional float z = 3;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *z
       * </pre>
       *
       * <code>optional float z = 3;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float o_ ;
      /**
       * <pre>
       *朝向
       * </pre>
       *
       * <code>optional float o = 4;</code>
       */
      public float getO() {
        return o_;
      }
      /**
       * <pre>
       *朝向
       * </pre>
       *
       * <code>optional float o = 4;</code>
       */
      public Builder setO(float value) {
        
        o_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *朝向
       * </pre>
       *
       * <code>optional float o = 4;</code>
       */
      public Builder clearO() {
        
        o_ = 0F;
        onChanged();
        return this;
      }

      private int map_ ;
      /**
       * <pre>
       *地图id
       * </pre>
       *
       * <code>optional int32 map = 5;</code>
       */
      public int getMap() {
        return map_;
      }
      /**
       * <pre>
       *地图id
       * </pre>
       *
       * <code>optional int32 map = 5;</code>
       */
      public Builder setMap(int value) {
        
        map_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地图id
       * </pre>
       *
       * <code>optional int32 map = 5;</code>
       */
      public Builder clearMap() {
        
        map_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.Coordinate)
    }

    // @@protoc_insertion_point(class_scope:Pro.Coordinate)
    private static final com.fsgame.proto.MSGBaseCommon.Coordinate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGBaseCommon.Coordinate();
    }

    public static com.fsgame.proto.MSGBaseCommon.Coordinate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coordinate>
        PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
      public Coordinate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Coordinate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Coordinate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coordinate> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGBaseCommon.Coordinate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_Coordinate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_Coordinate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BaseCommon.proto\022\003Pro\"E\n\nCoordinate\022\t\n" +
      "\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\t\n\001o\030\004 \001(" +
      "\002\022\013\n\003map\030\005 \001(\005*)\n\nLoginState\022\013\n\007_FAILD_\020" +
      "\000\022\016\n\n_SUCESSED_\020\001*X\n\010MoveType\022\t\n\005_RUN_\020\000" +
      "\022\n\n\006_WALK_\020\001\022\014\n\010_SHOORT_\020\002\022\013\n\007_SKILL_\020\003\022" +
      "\n\n\006_JUMP_\020\004\022\016\n\n_STOPJUMP_\020\005*.\n\010ChatType\022" +
      "\020\n\014_PLAYERCHAT_\020\000\022\020\n\014_SYSTEMCHAT_\020\001*\'\n\tS" +
      "killType\022\016\n\n_SHOORTER_\020\000\022\n\n\006_MOFA_\020\001B!\n\020" +
      "com.fsgame.protoB\rMSGBaseCommonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Pro_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_Coordinate_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "O", "Map", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
