// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginGameS2C.proto

package com.fsgame.proto;

public final class MSGLoginGameS2C {
  private MSGLoginGameS2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginGameS2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.LoginGameS2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *角色  待定
     * </pre>
     *
     * <code>optional .Pro.LoginState state = 1;</code>
     */
    int getStateValue();
    /**
     * <pre>
     *角色  待定
     * </pre>
     *
     * <code>optional .Pro.LoginState state = 1;</code>
     */
    com.fsgame.proto.MSGBaseCommon.LoginState getState();
  }
  /**
   * <pre>
   *服务器响应登录
   * </pre>
   *
   * Protobuf type {@code Pro.LoginGameS2C}
   */
  public  static final class LoginGameS2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.LoginGameS2C)
      LoginGameS2COrBuilder {
    // Use LoginGameS2C.newBuilder() to construct.
    private LoginGameS2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginGameS2C() {
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginGameS2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGLoginGameS2C.internal_static_Pro_LoginGameS2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGLoginGameS2C.internal_static_Pro_LoginGameS2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.class, com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <pre>
     *角色  待定
     * </pre>
     *
     * <code>optional .Pro.LoginState state = 1;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     *角色  待定
     * </pre>
     *
     * <code>optional .Pro.LoginState state = 1;</code>
     */
    public com.fsgame.proto.MSGBaseCommon.LoginState getState() {
      com.fsgame.proto.MSGBaseCommon.LoginState result = com.fsgame.proto.MSGBaseCommon.LoginState.valueOf(state_);
      return result == null ? com.fsgame.proto.MSGBaseCommon.LoginState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != com.fsgame.proto.MSGBaseCommon.LoginState._FAILD_.getNumber()) {
        output.writeEnum(1, state_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != com.fsgame.proto.MSGBaseCommon.LoginState._FAILD_.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C other = (com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C) obj;

      boolean result = true;
      result = result && state_ == other.state_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务器响应登录
     * </pre>
     *
     * Protobuf type {@code Pro.LoginGameS2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.LoginGameS2C)
        com.fsgame.proto.MSGLoginGameS2C.LoginGameS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGLoginGameS2C.internal_static_Pro_LoginGameS2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGLoginGameS2C.internal_static_Pro_LoginGameS2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.class, com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        state_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGLoginGameS2C.internal_static_Pro_LoginGameS2C_descriptor;
      }

      public com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C getDefaultInstanceForType() {
        return com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.getDefaultInstance();
      }

      public com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C build() {
        com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C buildPartial() {
        com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C result = new com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C(this);
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C) {
          return mergeFrom((com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C other) {
        if (other == com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       *角色  待定
       * </pre>
       *
       * <code>optional .Pro.LoginState state = 1;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       *角色  待定
       * </pre>
       *
       * <code>optional .Pro.LoginState state = 1;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色  待定
       * </pre>
       *
       * <code>optional .Pro.LoginState state = 1;</code>
       */
      public com.fsgame.proto.MSGBaseCommon.LoginState getState() {
        com.fsgame.proto.MSGBaseCommon.LoginState result = com.fsgame.proto.MSGBaseCommon.LoginState.valueOf(state_);
        return result == null ? com.fsgame.proto.MSGBaseCommon.LoginState.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *角色  待定
       * </pre>
       *
       * <code>optional .Pro.LoginState state = 1;</code>
       */
      public Builder setState(com.fsgame.proto.MSGBaseCommon.LoginState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色  待定
       * </pre>
       *
       * <code>optional .Pro.LoginState state = 1;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.LoginGameS2C)
    }

    // @@protoc_insertion_point(class_scope:Pro.LoginGameS2C)
    private static final com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C();
    }

    public static com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginGameS2C>
        PARSER = new com.google.protobuf.AbstractParser<LoginGameS2C>() {
      public LoginGameS2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginGameS2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginGameS2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameS2C> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGLoginGameS2C.LoginGameS2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_LoginGameS2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_LoginGameS2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginGameS2C.proto\022\003Pro\032\020BaseCommon.pr" +
      "oto\".\n\014LoginGameS2C\022\036\n\005state\030\001 \001(\0162\017.Pro" +
      ".LoginStateB#\n\020com.fsgame.protoB\017MSGLogi" +
      "nGameS2Cb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fsgame.proto.MSGBaseCommon.getDescriptor(),
        }, assigner);
    internal_static_Pro_LoginGameS2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_LoginGameS2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_LoginGameS2C_descriptor,
        new java.lang.String[] { "State", });
    com.fsgame.proto.MSGBaseCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
