// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoadGameMapC2S.proto

package com.fsgame.proto;

public final class MSGLoadGameMapC2S {
  private MSGLoadGameMapC2S() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoadGameMapC2SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.LoadGameMapC2S)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *no info
     * </pre>
     *
     * <code>optional float time = 1;</code>
     */
    float getTime();
  }
  /**
   * Protobuf type {@code Pro.LoadGameMapC2S}
   */
  public  static final class LoadGameMapC2S extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.LoadGameMapC2S)
      LoadGameMapC2SOrBuilder {
    // Use LoadGameMapC2S.newBuilder() to construct.
    private LoadGameMapC2S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoadGameMapC2S() {
      time_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoadGameMapC2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              time_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGLoadGameMapC2S.internal_static_Pro_LoadGameMapC2S_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGLoadGameMapC2S.internal_static_Pro_LoadGameMapC2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.class, com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private float time_;
    /**
     * <pre>
     *no info
     * </pre>
     *
     * <code>optional float time = 1;</code>
     */
    public float getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0F) {
        output.writeFloat(1, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S other = (com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getTime())
          == java.lang.Float.floatToIntBits(
              other.getTime()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pro.LoadGameMapC2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.LoadGameMapC2S)
        com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGLoadGameMapC2S.internal_static_Pro_LoadGameMapC2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGLoadGameMapC2S.internal_static_Pro_LoadGameMapC2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.class, com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGLoadGameMapC2S.internal_static_Pro_LoadGameMapC2S_descriptor;
      }

      public com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S getDefaultInstanceForType() {
        return com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.getDefaultInstance();
      }

      public com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S build() {
        com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S buildPartial() {
        com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S result = new com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S(this);
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S) {
          return mergeFrom((com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S other) {
        if (other == com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S.getDefaultInstance()) return this;
        if (other.getTime() != 0F) {
          setTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float time_ ;
      /**
       * <pre>
       *no info
       * </pre>
       *
       * <code>optional float time = 1;</code>
       */
      public float getTime() {
        return time_;
      }
      /**
       * <pre>
       *no info
       * </pre>
       *
       * <code>optional float time = 1;</code>
       */
      public Builder setTime(float value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *no info
       * </pre>
       *
       * <code>optional float time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.LoadGameMapC2S)
    }

    // @@protoc_insertion_point(class_scope:Pro.LoadGameMapC2S)
    private static final com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S();
    }

    public static com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoadGameMapC2S>
        PARSER = new com.google.protobuf.AbstractParser<LoadGameMapC2S>() {
      public LoadGameMapC2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoadGameMapC2S(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoadGameMapC2S> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoadGameMapC2S> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGLoadGameMapC2S.LoadGameMapC2S getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_LoadGameMapC2S_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_LoadGameMapC2S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LoadGameMapC2S.proto\022\003Pro\"\036\n\016LoadGameM" +
      "apC2S\022\014\n\004time\030\001 \001(\002B%\n\020com.fsgame.protoB" +
      "\021MSGLoadGameMapC2Sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Pro_LoadGameMapC2S_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_LoadGameMapC2S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_LoadGameMapC2S_descriptor,
        new java.lang.String[] { "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
