// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoadGameMapS2C.proto

package com.fsgame.proto;

public final class MSGLoadGameMapS2C {
  private MSGLoadGameMapS2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoadGameMapS2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.LoadGameMapS2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    boolean hasMainplayer();
    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    com.fsgame.proto.MSGPlayerCommon.PlayerCommon getMainplayer();
    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getMainplayerOrBuilder();
  }
  /**
   * Protobuf type {@code Pro.LoadGameMapS2C}
   */
  public  static final class LoadGameMapS2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.LoadGameMapS2C)
      LoadGameMapS2COrBuilder {
    // Use LoadGameMapS2C.newBuilder() to construct.
    private LoadGameMapS2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoadGameMapS2C() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoadGameMapS2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder subBuilder = null;
              if (mainplayer_ != null) {
                subBuilder = mainplayer_.toBuilder();
              }
              mainplayer_ = input.readMessage(com.fsgame.proto.MSGPlayerCommon.PlayerCommon.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mainplayer_);
                mainplayer_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGLoadGameMapS2C.internal_static_Pro_LoadGameMapS2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGLoadGameMapS2C.internal_static_Pro_LoadGameMapS2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.class, com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.Builder.class);
    }

    public static final int MAINPLAYER_FIELD_NUMBER = 1;
    private com.fsgame.proto.MSGPlayerCommon.PlayerCommon mainplayer_;
    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    public boolean hasMainplayer() {
      return mainplayer_ != null;
    }
    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getMainplayer() {
      return mainplayer_ == null ? com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : mainplayer_;
    }
    /**
     * <pre>
     *主玩家 基本信息
     * </pre>
     *
     * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
     */
    public com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getMainplayerOrBuilder() {
      return getMainplayer();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mainplayer_ != null) {
        output.writeMessage(1, getMainplayer());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mainplayer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMainplayer());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C other = (com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C) obj;

      boolean result = true;
      result = result && (hasMainplayer() == other.hasMainplayer());
      if (hasMainplayer()) {
        result = result && getMainplayer()
            .equals(other.getMainplayer());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMainplayer()) {
        hash = (37 * hash) + MAINPLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getMainplayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pro.LoadGameMapS2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.LoadGameMapS2C)
        com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGLoadGameMapS2C.internal_static_Pro_LoadGameMapS2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGLoadGameMapS2C.internal_static_Pro_LoadGameMapS2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.class, com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (mainplayerBuilder_ == null) {
          mainplayer_ = null;
        } else {
          mainplayer_ = null;
          mainplayerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGLoadGameMapS2C.internal_static_Pro_LoadGameMapS2C_descriptor;
      }

      public com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C getDefaultInstanceForType() {
        return com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.getDefaultInstance();
      }

      public com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C build() {
        com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C buildPartial() {
        com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C result = new com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C(this);
        if (mainplayerBuilder_ == null) {
          result.mainplayer_ = mainplayer_;
        } else {
          result.mainplayer_ = mainplayerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C) {
          return mergeFrom((com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C other) {
        if (other == com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C.getDefaultInstance()) return this;
        if (other.hasMainplayer()) {
          mergeMainplayer(other.getMainplayer());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fsgame.proto.MSGPlayerCommon.PlayerCommon mainplayer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder> mainplayerBuilder_;
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public boolean hasMainplayer() {
        return mainplayerBuilder_ != null || mainplayer_ != null;
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getMainplayer() {
        if (mainplayerBuilder_ == null) {
          return mainplayer_ == null ? com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : mainplayer_;
        } else {
          return mainplayerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public Builder setMainplayer(com.fsgame.proto.MSGPlayerCommon.PlayerCommon value) {
        if (mainplayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mainplayer_ = value;
          onChanged();
        } else {
          mainplayerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public Builder setMainplayer(
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder builderForValue) {
        if (mainplayerBuilder_ == null) {
          mainplayer_ = builderForValue.build();
          onChanged();
        } else {
          mainplayerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public Builder mergeMainplayer(com.fsgame.proto.MSGPlayerCommon.PlayerCommon value) {
        if (mainplayerBuilder_ == null) {
          if (mainplayer_ != null) {
            mainplayer_ =
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.newBuilder(mainplayer_).mergeFrom(value).buildPartial();
          } else {
            mainplayer_ = value;
          }
          onChanged();
        } else {
          mainplayerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public Builder clearMainplayer() {
        if (mainplayerBuilder_ == null) {
          mainplayer_ = null;
          onChanged();
        } else {
          mainplayer_ = null;
          mainplayerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder getMainplayerBuilder() {
        
        onChanged();
        return getMainplayerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getMainplayerOrBuilder() {
        if (mainplayerBuilder_ != null) {
          return mainplayerBuilder_.getMessageOrBuilder();
        } else {
          return mainplayer_ == null ?
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : mainplayer_;
        }
      }
      /**
       * <pre>
       *主玩家 基本信息
       * </pre>
       *
       * <code>optional .Pro.PlayerCommon mainplayer = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder> 
          getMainplayerFieldBuilder() {
        if (mainplayerBuilder_ == null) {
          mainplayerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder>(
                  getMainplayer(),
                  getParentForChildren(),
                  isClean());
          mainplayer_ = null;
        }
        return mainplayerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.LoadGameMapS2C)
    }

    // @@protoc_insertion_point(class_scope:Pro.LoadGameMapS2C)
    private static final com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C();
    }

    public static com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoadGameMapS2C>
        PARSER = new com.google.protobuf.AbstractParser<LoadGameMapS2C>() {
      public LoadGameMapS2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoadGameMapS2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoadGameMapS2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoadGameMapS2C> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGLoadGameMapS2C.LoadGameMapS2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_LoadGameMapS2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_LoadGameMapS2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LoadGameMapS2C.proto\022\003Pro\032\022PlayerCommo" +
      "n.proto\"7\n\016LoadGameMapS2C\022%\n\nmainplayer\030" +
      "\001 \001(\0132\021.Pro.PlayerCommonB%\n\020com.fsgame.p" +
      "rotoB\021MSGLoadGameMapS2Cb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fsgame.proto.MSGPlayerCommon.getDescriptor(),
        }, assigner);
    internal_static_Pro_LoadGameMapS2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_LoadGameMapS2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_LoadGameMapS2C_descriptor,
        new java.lang.String[] { "Mainplayer", });
    com.fsgame.proto.MSGPlayerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
