// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ObjectSyncS2C.proto

package com.fsgame.proto;

public final class MSGObjectSyncS2C {
  private MSGObjectSyncS2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ObjectSyncS2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.ObjectSyncS2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> 
        getObjectsList();
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    com.fsgame.proto.MSGObjectCommon.ObjectSync getObjects(int index);
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    int getObjectsCount();
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
        getObjectsOrBuilderList();
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getObjectsOrBuilder(
        int index);

    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> 
        getEnterList();
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    com.fsgame.proto.MSGObjectCommon.ObjectSync getEnter(int index);
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    int getEnterCount();
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
        getEnterOrBuilderList();
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getEnterOrBuilder(
        int index);

    /**
     * <code>repeated int32 leave = 3;</code>
     */
    java.util.List<java.lang.Integer> getLeaveList();
    /**
     * <code>repeated int32 leave = 3;</code>
     */
    int getLeaveCount();
    /**
     * <code>repeated int32 leave = 3;</code>
     */
    int getLeave(int index);
  }
  /**
   * Protobuf type {@code Pro.ObjectSyncS2C}
   */
  public  static final class ObjectSyncS2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.ObjectSyncS2C)
      ObjectSyncS2COrBuilder {
    // Use ObjectSyncS2C.newBuilder() to construct.
    private ObjectSyncS2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectSyncS2C() {
      objects_ = java.util.Collections.emptyList();
      enter_ = java.util.Collections.emptyList();
      leave_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ObjectSyncS2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                objects_ = new java.util.ArrayList<com.fsgame.proto.MSGObjectCommon.ObjectSync>();
                mutable_bitField0_ |= 0x00000001;
              }
              objects_.add(
                  input.readMessage(com.fsgame.proto.MSGObjectCommon.ObjectSync.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                enter_ = new java.util.ArrayList<com.fsgame.proto.MSGObjectCommon.ObjectSync>();
                mutable_bitField0_ |= 0x00000002;
              }
              enter_.add(
                  input.readMessage(com.fsgame.proto.MSGObjectCommon.ObjectSync.parser(), extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                leave_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              leave_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                leave_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                leave_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = java.util.Collections.unmodifiableList(objects_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          enter_ = java.util.Collections.unmodifiableList(enter_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          leave_ = java.util.Collections.unmodifiableList(leave_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGObjectSyncS2C.internal_static_Pro_ObjectSyncS2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGObjectSyncS2C.internal_static_Pro_ObjectSyncS2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.class, com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.Builder.class);
    }

    public static final int OBJECTS_FIELD_NUMBER = 1;
    private java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> objects_;
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> getObjectsList() {
      return objects_;
    }
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    public java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
        getObjectsOrBuilderList() {
      return objects_;
    }
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    public int getObjectsCount() {
      return objects_.size();
    }
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    public com.fsgame.proto.MSGObjectCommon.ObjectSync getObjects(int index) {
      return objects_.get(index);
    }
    /**
     * <code>repeated .Pro.ObjectSync objects = 1;</code>
     */
    public com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getObjectsOrBuilder(
        int index) {
      return objects_.get(index);
    }

    public static final int ENTER_FIELD_NUMBER = 2;
    private java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> enter_;
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> getEnterList() {
      return enter_;
    }
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    public java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
        getEnterOrBuilderList() {
      return enter_;
    }
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    public int getEnterCount() {
      return enter_.size();
    }
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    public com.fsgame.proto.MSGObjectCommon.ObjectSync getEnter(int index) {
      return enter_.get(index);
    }
    /**
     * <code>repeated .Pro.ObjectSync enter = 2;</code>
     */
    public com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getEnterOrBuilder(
        int index) {
      return enter_.get(index);
    }

    public static final int LEAVE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> leave_;
    /**
     * <code>repeated int32 leave = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getLeaveList() {
      return leave_;
    }
    /**
     * <code>repeated int32 leave = 3;</code>
     */
    public int getLeaveCount() {
      return leave_.size();
    }
    /**
     * <code>repeated int32 leave = 3;</code>
     */
    public int getLeave(int index) {
      return leave_.get(index);
    }
    private int leaveMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < objects_.size(); i++) {
        output.writeMessage(1, objects_.get(i));
      }
      for (int i = 0; i < enter_.size(); i++) {
        output.writeMessage(2, enter_.get(i));
      }
      if (getLeaveList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(leaveMemoizedSerializedSize);
      }
      for (int i = 0; i < leave_.size(); i++) {
        output.writeInt32NoTag(leave_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < objects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, objects_.get(i));
      }
      for (int i = 0; i < enter_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, enter_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < leave_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(leave_.get(i));
        }
        size += dataSize;
        if (!getLeaveList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        leaveMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C other = (com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C) obj;

      boolean result = true;
      result = result && getObjectsList()
          .equals(other.getObjectsList());
      result = result && getEnterList()
          .equals(other.getEnterList());
      result = result && getLeaveList()
          .equals(other.getLeaveList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getObjectsCount() > 0) {
        hash = (37 * hash) + OBJECTS_FIELD_NUMBER;
        hash = (53 * hash) + getObjectsList().hashCode();
      }
      if (getEnterCount() > 0) {
        hash = (37 * hash) + ENTER_FIELD_NUMBER;
        hash = (53 * hash) + getEnterList().hashCode();
      }
      if (getLeaveCount() > 0) {
        hash = (37 * hash) + LEAVE_FIELD_NUMBER;
        hash = (53 * hash) + getLeaveList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pro.ObjectSyncS2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.ObjectSyncS2C)
        com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGObjectSyncS2C.internal_static_Pro_ObjectSyncS2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGObjectSyncS2C.internal_static_Pro_ObjectSyncS2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.class, com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getObjectsFieldBuilder();
          getEnterFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          objectsBuilder_.clear();
        }
        if (enterBuilder_ == null) {
          enter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          enterBuilder_.clear();
        }
        leave_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGObjectSyncS2C.internal_static_Pro_ObjectSyncS2C_descriptor;
      }

      public com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C getDefaultInstanceForType() {
        return com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.getDefaultInstance();
      }

      public com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C build() {
        com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C buildPartial() {
        com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C result = new com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C(this);
        int from_bitField0_ = bitField0_;
        if (objectsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            objects_ = java.util.Collections.unmodifiableList(objects_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.objects_ = objects_;
        } else {
          result.objects_ = objectsBuilder_.build();
        }
        if (enterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            enter_ = java.util.Collections.unmodifiableList(enter_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.enter_ = enter_;
        } else {
          result.enter_ = enterBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          leave_ = java.util.Collections.unmodifiableList(leave_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.leave_ = leave_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C) {
          return mergeFrom((com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C other) {
        if (other == com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C.getDefaultInstance()) return this;
        if (objectsBuilder_ == null) {
          if (!other.objects_.isEmpty()) {
            if (objects_.isEmpty()) {
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureObjectsIsMutable();
              objects_.addAll(other.objects_);
            }
            onChanged();
          }
        } else {
          if (!other.objects_.isEmpty()) {
            if (objectsBuilder_.isEmpty()) {
              objectsBuilder_.dispose();
              objectsBuilder_ = null;
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
              objectsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getObjectsFieldBuilder() : null;
            } else {
              objectsBuilder_.addAllMessages(other.objects_);
            }
          }
        }
        if (enterBuilder_ == null) {
          if (!other.enter_.isEmpty()) {
            if (enter_.isEmpty()) {
              enter_ = other.enter_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEnterIsMutable();
              enter_.addAll(other.enter_);
            }
            onChanged();
          }
        } else {
          if (!other.enter_.isEmpty()) {
            if (enterBuilder_.isEmpty()) {
              enterBuilder_.dispose();
              enterBuilder_ = null;
              enter_ = other.enter_;
              bitField0_ = (bitField0_ & ~0x00000002);
              enterBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEnterFieldBuilder() : null;
            } else {
              enterBuilder_.addAllMessages(other.enter_);
            }
          }
        }
        if (!other.leave_.isEmpty()) {
          if (leave_.isEmpty()) {
            leave_ = other.leave_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLeaveIsMutable();
            leave_.addAll(other.leave_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> objects_ =
        java.util.Collections.emptyList();
      private void ensureObjectsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = new java.util.ArrayList<com.fsgame.proto.MSGObjectCommon.ObjectSync>(objects_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> objectsBuilder_;

      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> getObjectsList() {
        if (objectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objects_);
        } else {
          return objectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public int getObjectsCount() {
        if (objectsBuilder_ == null) {
          return objects_.size();
        } else {
          return objectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync getObjects(int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);
        } else {
          return objectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder setObjects(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.set(index, value);
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder setObjects(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.set(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder addObjects(com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder addObjects(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(index, value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder addObjects(
          com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder addObjects(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder addAllObjects(
          java.lang.Iterable<? extends com.fsgame.proto.MSGObjectCommon.ObjectSync> values) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, objects_);
          onChanged();
        } else {
          objectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder clearObjects() {
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          objectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public Builder removeObjects(int index) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.remove(index);
          onChanged();
        } else {
          objectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder getObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getObjectsOrBuilder(
          int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);  } else {
          return objectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
           getObjectsOrBuilderList() {
        if (objectsBuilder_ != null) {
          return objectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objects_);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder addObjectsBuilder() {
        return getObjectsFieldBuilder().addBuilder(
            com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance());
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder addObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().addBuilder(
            index, com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance());
      }
      /**
       * <code>repeated .Pro.ObjectSync objects = 1;</code>
       */
      public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder> 
           getObjectsBuilderList() {
        return getObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
          getObjectsFieldBuilder() {
        if (objectsBuilder_ == null) {
          objectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder>(
                  objects_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          objects_ = null;
        }
        return objectsBuilder_;
      }

      private java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> enter_ =
        java.util.Collections.emptyList();
      private void ensureEnterIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          enter_ = new java.util.ArrayList<com.fsgame.proto.MSGObjectCommon.ObjectSync>(enter_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> enterBuilder_;

      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync> getEnterList() {
        if (enterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(enter_);
        } else {
          return enterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public int getEnterCount() {
        if (enterBuilder_ == null) {
          return enter_.size();
        } else {
          return enterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync getEnter(int index) {
        if (enterBuilder_ == null) {
          return enter_.get(index);
        } else {
          return enterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder setEnter(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (enterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnterIsMutable();
          enter_.set(index, value);
          onChanged();
        } else {
          enterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder setEnter(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (enterBuilder_ == null) {
          ensureEnterIsMutable();
          enter_.set(index, builderForValue.build());
          onChanged();
        } else {
          enterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder addEnter(com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (enterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnterIsMutable();
          enter_.add(value);
          onChanged();
        } else {
          enterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder addEnter(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync value) {
        if (enterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnterIsMutable();
          enter_.add(index, value);
          onChanged();
        } else {
          enterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder addEnter(
          com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (enterBuilder_ == null) {
          ensureEnterIsMutable();
          enter_.add(builderForValue.build());
          onChanged();
        } else {
          enterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder addEnter(
          int index, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder builderForValue) {
        if (enterBuilder_ == null) {
          ensureEnterIsMutable();
          enter_.add(index, builderForValue.build());
          onChanged();
        } else {
          enterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder addAllEnter(
          java.lang.Iterable<? extends com.fsgame.proto.MSGObjectCommon.ObjectSync> values) {
        if (enterBuilder_ == null) {
          ensureEnterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, enter_);
          onChanged();
        } else {
          enterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder clearEnter() {
        if (enterBuilder_ == null) {
          enter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          enterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public Builder removeEnter(int index) {
        if (enterBuilder_ == null) {
          ensureEnterIsMutable();
          enter_.remove(index);
          onChanged();
        } else {
          enterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder getEnterBuilder(
          int index) {
        return getEnterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder getEnterOrBuilder(
          int index) {
        if (enterBuilder_ == null) {
          return enter_.get(index);  } else {
          return enterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public java.util.List<? extends com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
           getEnterOrBuilderList() {
        if (enterBuilder_ != null) {
          return enterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(enter_);
        }
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder addEnterBuilder() {
        return getEnterFieldBuilder().addBuilder(
            com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance());
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder addEnterBuilder(
          int index) {
        return getEnterFieldBuilder().addBuilder(
            index, com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance());
      }
      /**
       * <code>repeated .Pro.ObjectSync enter = 2;</code>
       */
      public java.util.List<com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder> 
           getEnterBuilderList() {
        return getEnterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder> 
          getEnterFieldBuilder() {
        if (enterBuilder_ == null) {
          enterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fsgame.proto.MSGObjectCommon.ObjectSync, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder, com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder>(
                  enter_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          enter_ = null;
        }
        return enterBuilder_;
      }

      private java.util.List<java.lang.Integer> leave_ = java.util.Collections.emptyList();
      private void ensureLeaveIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          leave_ = new java.util.ArrayList<java.lang.Integer>(leave_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getLeaveList() {
        return java.util.Collections.unmodifiableList(leave_);
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public int getLeaveCount() {
        return leave_.size();
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public int getLeave(int index) {
        return leave_.get(index);
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public Builder setLeave(
          int index, int value) {
        ensureLeaveIsMutable();
        leave_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public Builder addLeave(int value) {
        ensureLeaveIsMutable();
        leave_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public Builder addAllLeave(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLeaveIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, leave_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 leave = 3;</code>
       */
      public Builder clearLeave() {
        leave_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.ObjectSyncS2C)
    }

    // @@protoc_insertion_point(class_scope:Pro.ObjectSyncS2C)
    private static final com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C();
    }

    public static com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectSyncS2C>
        PARSER = new com.google.protobuf.AbstractParser<ObjectSyncS2C>() {
      public ObjectSyncS2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ObjectSyncS2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectSyncS2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectSyncS2C> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGObjectSyncS2C.ObjectSyncS2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_ObjectSyncS2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_ObjectSyncS2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ObjectSyncS2C.proto\022\003Pro\032\022ObjectCommon" +
      ".proto\"`\n\rObjectSyncS2C\022 \n\007objects\030\001 \003(\013" +
      "2\017.Pro.ObjectSync\022\036\n\005enter\030\002 \003(\0132\017.Pro.O" +
      "bjectSync\022\r\n\005leave\030\003 \003(\005B$\n\020com.fsgame.p" +
      "rotoB\020MSGObjectSyncS2Cb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fsgame.proto.MSGObjectCommon.getDescriptor(),
        }, assigner);
    internal_static_Pro_ObjectSyncS2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_ObjectSyncS2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_ObjectSyncS2C_descriptor,
        new java.lang.String[] { "Objects", "Enter", "Leave", });
    com.fsgame.proto.MSGObjectCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
