// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ObjectCommon.proto

package com.fsgame.proto;

public final class MSGObjectCommon {
  private MSGObjectCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ObjectSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.ObjectSync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    boolean hasPlayerbase();
    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    com.fsgame.proto.MSGPlayerCommon.PlayerCommon getPlayerbase();
    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getPlayerbaseOrBuilder();
  }
  /**
   * Protobuf type {@code Pro.ObjectSync}
   */
  public  static final class ObjectSync extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.ObjectSync)
      ObjectSyncOrBuilder {
    // Use ObjectSync.newBuilder() to construct.
    private ObjectSync(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectSync() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ObjectSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder subBuilder = null;
              if (playerbase_ != null) {
                subBuilder = playerbase_.toBuilder();
              }
              playerbase_ = input.readMessage(com.fsgame.proto.MSGPlayerCommon.PlayerCommon.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerbase_);
                playerbase_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGObjectCommon.internal_static_Pro_ObjectSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGObjectCommon.internal_static_Pro_ObjectSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGObjectCommon.ObjectSync.class, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder.class);
    }

    public static final int PLAYERBASE_FIELD_NUMBER = 1;
    private com.fsgame.proto.MSGPlayerCommon.PlayerCommon playerbase_;
    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    public boolean hasPlayerbase() {
      return playerbase_ != null;
    }
    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getPlayerbase() {
      return playerbase_ == null ? com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : playerbase_;
    }
    /**
     * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
     */
    public com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getPlayerbaseOrBuilder() {
      return getPlayerbase();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerbase_ != null) {
        output.writeMessage(1, getPlayerbase());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerbase_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayerbase());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGObjectCommon.ObjectSync)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGObjectCommon.ObjectSync other = (com.fsgame.proto.MSGObjectCommon.ObjectSync) obj;

      boolean result = true;
      result = result && (hasPlayerbase() == other.hasPlayerbase());
      if (hasPlayerbase()) {
        result = result && getPlayerbase()
            .equals(other.getPlayerbase());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPlayerbase()) {
        hash = (37 * hash) + PLAYERBASE_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerbase().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGObjectCommon.ObjectSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGObjectCommon.ObjectSync prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pro.ObjectSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.ObjectSync)
        com.fsgame.proto.MSGObjectCommon.ObjectSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGObjectCommon.internal_static_Pro_ObjectSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGObjectCommon.internal_static_Pro_ObjectSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGObjectCommon.ObjectSync.class, com.fsgame.proto.MSGObjectCommon.ObjectSync.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGObjectCommon.ObjectSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (playerbaseBuilder_ == null) {
          playerbase_ = null;
        } else {
          playerbase_ = null;
          playerbaseBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGObjectCommon.internal_static_Pro_ObjectSync_descriptor;
      }

      public com.fsgame.proto.MSGObjectCommon.ObjectSync getDefaultInstanceForType() {
        return com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance();
      }

      public com.fsgame.proto.MSGObjectCommon.ObjectSync build() {
        com.fsgame.proto.MSGObjectCommon.ObjectSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGObjectCommon.ObjectSync buildPartial() {
        com.fsgame.proto.MSGObjectCommon.ObjectSync result = new com.fsgame.proto.MSGObjectCommon.ObjectSync(this);
        if (playerbaseBuilder_ == null) {
          result.playerbase_ = playerbase_;
        } else {
          result.playerbase_ = playerbaseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGObjectCommon.ObjectSync) {
          return mergeFrom((com.fsgame.proto.MSGObjectCommon.ObjectSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGObjectCommon.ObjectSync other) {
        if (other == com.fsgame.proto.MSGObjectCommon.ObjectSync.getDefaultInstance()) return this;
        if (other.hasPlayerbase()) {
          mergePlayerbase(other.getPlayerbase());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGObjectCommon.ObjectSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGObjectCommon.ObjectSync) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fsgame.proto.MSGPlayerCommon.PlayerCommon playerbase_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder> playerbaseBuilder_;
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public boolean hasPlayerbase() {
        return playerbaseBuilder_ != null || playerbase_ != null;
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getPlayerbase() {
        if (playerbaseBuilder_ == null) {
          return playerbase_ == null ? com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : playerbase_;
        } else {
          return playerbaseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public Builder setPlayerbase(com.fsgame.proto.MSGPlayerCommon.PlayerCommon value) {
        if (playerbaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerbase_ = value;
          onChanged();
        } else {
          playerbaseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public Builder setPlayerbase(
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder builderForValue) {
        if (playerbaseBuilder_ == null) {
          playerbase_ = builderForValue.build();
          onChanged();
        } else {
          playerbaseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public Builder mergePlayerbase(com.fsgame.proto.MSGPlayerCommon.PlayerCommon value) {
        if (playerbaseBuilder_ == null) {
          if (playerbase_ != null) {
            playerbase_ =
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.newBuilder(playerbase_).mergeFrom(value).buildPartial();
          } else {
            playerbase_ = value;
          }
          onChanged();
        } else {
          playerbaseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public Builder clearPlayerbase() {
        if (playerbaseBuilder_ == null) {
          playerbase_ = null;
          onChanged();
        } else {
          playerbase_ = null;
          playerbaseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder getPlayerbaseBuilder() {
        
        onChanged();
        return getPlayerbaseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      public com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder getPlayerbaseOrBuilder() {
        if (playerbaseBuilder_ != null) {
          return playerbaseBuilder_.getMessageOrBuilder();
        } else {
          return playerbase_ == null ?
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance() : playerbase_;
        }
      }
      /**
       * <code>optional .Pro.PlayerCommon playerbase = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder> 
          getPlayerbaseFieldBuilder() {
        if (playerbaseBuilder_ == null) {
          playerbaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder, com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder>(
                  getPlayerbase(),
                  getParentForChildren(),
                  isClean());
          playerbase_ = null;
        }
        return playerbaseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.ObjectSync)
    }

    // @@protoc_insertion_point(class_scope:Pro.ObjectSync)
    private static final com.fsgame.proto.MSGObjectCommon.ObjectSync DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGObjectCommon.ObjectSync();
    }

    public static com.fsgame.proto.MSGObjectCommon.ObjectSync getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectSync>
        PARSER = new com.google.protobuf.AbstractParser<ObjectSync>() {
      public ObjectSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ObjectSync(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectSync> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectSync> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGObjectCommon.ObjectSync getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_ObjectSync_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_ObjectSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ObjectCommon.proto\022\003Pro\032\022PlayerCommon." +
      "proto\"3\n\nObjectSync\022%\n\nplayerbase\030\001 \001(\0132" +
      "\021.Pro.PlayerCommonB#\n\020com.fsgame.protoB\017" +
      "MSGObjectCommonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fsgame.proto.MSGPlayerCommon.getDescriptor(),
        }, assigner);
    internal_static_Pro_ObjectSync_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_ObjectSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_ObjectSync_descriptor,
        new java.lang.String[] { "Playerbase", });
    com.fsgame.proto.MSGPlayerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
