// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerCommon.proto

package com.fsgame.proto;

public final class MSGPlayerCommon {
  private MSGPlayerCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerCommonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pro.PlayerCommon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 baseid = 1;</code>
     */
    int getBaseid();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    boolean hasCoor();
    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    com.fsgame.proto.MSGBaseCommon.Coordinate getCoor();
    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder getCoorOrBuilder();

    /**
     * <code>optional float hp = 4;</code>
     */
    float getHp();
  }
  /**
   * <pre>
   *玩家坐标信息
   * </pre>
   *
   * Protobuf type {@code Pro.PlayerCommon}
   */
  public  static final class PlayerCommon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pro.PlayerCommon)
      PlayerCommonOrBuilder {
    // Use PlayerCommon.newBuilder() to construct.
    private PlayerCommon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerCommon() {
      baseid_ = 0;
      name_ = "";
      hp_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerCommon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              baseid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              com.fsgame.proto.MSGBaseCommon.Coordinate.Builder subBuilder = null;
              if (coor_ != null) {
                subBuilder = coor_.toBuilder();
              }
              coor_ = input.readMessage(com.fsgame.proto.MSGBaseCommon.Coordinate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coor_);
                coor_ = subBuilder.buildPartial();
              }

              break;
            }
            case 37: {

              hp_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fsgame.proto.MSGPlayerCommon.internal_static_Pro_PlayerCommon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fsgame.proto.MSGPlayerCommon.internal_static_Pro_PlayerCommon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fsgame.proto.MSGPlayerCommon.PlayerCommon.class, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder.class);
    }

    public static final int BASEID_FIELD_NUMBER = 1;
    private int baseid_;
    /**
     * <code>optional int32 baseid = 1;</code>
     */
    public int getBaseid() {
      return baseid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COOR_FIELD_NUMBER = 3;
    private com.fsgame.proto.MSGBaseCommon.Coordinate coor_;
    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    public boolean hasCoor() {
      return coor_ != null;
    }
    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    public com.fsgame.proto.MSGBaseCommon.Coordinate getCoor() {
      return coor_ == null ? com.fsgame.proto.MSGBaseCommon.Coordinate.getDefaultInstance() : coor_;
    }
    /**
     * <code>optional .Pro.Coordinate coor = 3;</code>
     */
    public com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder getCoorOrBuilder() {
      return getCoor();
    }

    public static final int HP_FIELD_NUMBER = 4;
    private float hp_;
    /**
     * <code>optional float hp = 4;</code>
     */
    public float getHp() {
      return hp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseid_ != 0) {
        output.writeInt32(1, baseid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (coor_ != null) {
        output.writeMessage(3, getCoor());
      }
      if (hp_ != 0F) {
        output.writeFloat(4, hp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, baseid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (coor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCoor());
      }
      if (hp_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, hp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fsgame.proto.MSGPlayerCommon.PlayerCommon)) {
        return super.equals(obj);
      }
      com.fsgame.proto.MSGPlayerCommon.PlayerCommon other = (com.fsgame.proto.MSGPlayerCommon.PlayerCommon) obj;

      boolean result = true;
      result = result && (getBaseid()
          == other.getBaseid());
      result = result && getName()
          .equals(other.getName());
      result = result && (hasCoor() == other.hasCoor());
      if (hasCoor()) {
        result = result && getCoor()
            .equals(other.getCoor());
      }
      result = result && (
          java.lang.Float.floatToIntBits(getHp())
          == java.lang.Float.floatToIntBits(
              other.getHp()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BASEID_FIELD_NUMBER;
      hash = (53 * hash) + getBaseid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasCoor()) {
        hash = (37 * hash) + COOR_FIELD_NUMBER;
        hash = (53 * hash) + getCoor().hashCode();
      }
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fsgame.proto.MSGPlayerCommon.PlayerCommon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩家坐标信息
     * </pre>
     *
     * Protobuf type {@code Pro.PlayerCommon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pro.PlayerCommon)
        com.fsgame.proto.MSGPlayerCommon.PlayerCommonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fsgame.proto.MSGPlayerCommon.internal_static_Pro_PlayerCommon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fsgame.proto.MSGPlayerCommon.internal_static_Pro_PlayerCommon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fsgame.proto.MSGPlayerCommon.PlayerCommon.class, com.fsgame.proto.MSGPlayerCommon.PlayerCommon.Builder.class);
      }

      // Construct using com.fsgame.proto.MSGPlayerCommon.PlayerCommon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        baseid_ = 0;

        name_ = "";

        if (coorBuilder_ == null) {
          coor_ = null;
        } else {
          coor_ = null;
          coorBuilder_ = null;
        }
        hp_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fsgame.proto.MSGPlayerCommon.internal_static_Pro_PlayerCommon_descriptor;
      }

      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getDefaultInstanceForType() {
        return com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance();
      }

      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon build() {
        com.fsgame.proto.MSGPlayerCommon.PlayerCommon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fsgame.proto.MSGPlayerCommon.PlayerCommon buildPartial() {
        com.fsgame.proto.MSGPlayerCommon.PlayerCommon result = new com.fsgame.proto.MSGPlayerCommon.PlayerCommon(this);
        result.baseid_ = baseid_;
        result.name_ = name_;
        if (coorBuilder_ == null) {
          result.coor_ = coor_;
        } else {
          result.coor_ = coorBuilder_.build();
        }
        result.hp_ = hp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fsgame.proto.MSGPlayerCommon.PlayerCommon) {
          return mergeFrom((com.fsgame.proto.MSGPlayerCommon.PlayerCommon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fsgame.proto.MSGPlayerCommon.PlayerCommon other) {
        if (other == com.fsgame.proto.MSGPlayerCommon.PlayerCommon.getDefaultInstance()) return this;
        if (other.getBaseid() != 0) {
          setBaseid(other.getBaseid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCoor()) {
          mergeCoor(other.getCoor());
        }
        if (other.getHp() != 0F) {
          setHp(other.getHp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fsgame.proto.MSGPlayerCommon.PlayerCommon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fsgame.proto.MSGPlayerCommon.PlayerCommon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int baseid_ ;
      /**
       * <code>optional int32 baseid = 1;</code>
       */
      public int getBaseid() {
        return baseid_;
      }
      /**
       * <code>optional int32 baseid = 1;</code>
       */
      public Builder setBaseid(int value) {
        
        baseid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 baseid = 1;</code>
       */
      public Builder clearBaseid() {
        
        baseid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.fsgame.proto.MSGBaseCommon.Coordinate coor_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGBaseCommon.Coordinate, com.fsgame.proto.MSGBaseCommon.Coordinate.Builder, com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder> coorBuilder_;
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public boolean hasCoor() {
        return coorBuilder_ != null || coor_ != null;
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public com.fsgame.proto.MSGBaseCommon.Coordinate getCoor() {
        if (coorBuilder_ == null) {
          return coor_ == null ? com.fsgame.proto.MSGBaseCommon.Coordinate.getDefaultInstance() : coor_;
        } else {
          return coorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public Builder setCoor(com.fsgame.proto.MSGBaseCommon.Coordinate value) {
        if (coorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coor_ = value;
          onChanged();
        } else {
          coorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public Builder setCoor(
          com.fsgame.proto.MSGBaseCommon.Coordinate.Builder builderForValue) {
        if (coorBuilder_ == null) {
          coor_ = builderForValue.build();
          onChanged();
        } else {
          coorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public Builder mergeCoor(com.fsgame.proto.MSGBaseCommon.Coordinate value) {
        if (coorBuilder_ == null) {
          if (coor_ != null) {
            coor_ =
              com.fsgame.proto.MSGBaseCommon.Coordinate.newBuilder(coor_).mergeFrom(value).buildPartial();
          } else {
            coor_ = value;
          }
          onChanged();
        } else {
          coorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public Builder clearCoor() {
        if (coorBuilder_ == null) {
          coor_ = null;
          onChanged();
        } else {
          coor_ = null;
          coorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public com.fsgame.proto.MSGBaseCommon.Coordinate.Builder getCoorBuilder() {
        
        onChanged();
        return getCoorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      public com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder getCoorOrBuilder() {
        if (coorBuilder_ != null) {
          return coorBuilder_.getMessageOrBuilder();
        } else {
          return coor_ == null ?
              com.fsgame.proto.MSGBaseCommon.Coordinate.getDefaultInstance() : coor_;
        }
      }
      /**
       * <code>optional .Pro.Coordinate coor = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fsgame.proto.MSGBaseCommon.Coordinate, com.fsgame.proto.MSGBaseCommon.Coordinate.Builder, com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder> 
          getCoorFieldBuilder() {
        if (coorBuilder_ == null) {
          coorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fsgame.proto.MSGBaseCommon.Coordinate, com.fsgame.proto.MSGBaseCommon.Coordinate.Builder, com.fsgame.proto.MSGBaseCommon.CoordinateOrBuilder>(
                  getCoor(),
                  getParentForChildren(),
                  isClean());
          coor_ = null;
        }
        return coorBuilder_;
      }

      private float hp_ ;
      /**
       * <code>optional float hp = 4;</code>
       */
      public float getHp() {
        return hp_;
      }
      /**
       * <code>optional float hp = 4;</code>
       */
      public Builder setHp(float value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float hp = 4;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Pro.PlayerCommon)
    }

    // @@protoc_insertion_point(class_scope:Pro.PlayerCommon)
    private static final com.fsgame.proto.MSGPlayerCommon.PlayerCommon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fsgame.proto.MSGPlayerCommon.PlayerCommon();
    }

    public static com.fsgame.proto.MSGPlayerCommon.PlayerCommon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerCommon>
        PARSER = new com.google.protobuf.AbstractParser<PlayerCommon>() {
      public PlayerCommon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerCommon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerCommon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerCommon> getParserForType() {
      return PARSER;
    }

    public com.fsgame.proto.MSGPlayerCommon.PlayerCommon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pro_PlayerCommon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pro_PlayerCommon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PlayerCommon.proto\022\003Pro\032\020BaseCommon.pr" +
      "oto\"W\n\014PlayerCommon\022\016\n\006baseid\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\022\035\n\004coor\030\003 \001(\0132\017.Pro.Coordinate" +
      "\022\n\n\002hp\030\004 \001(\002B#\n\020com.fsgame.protoB\017MSGPla" +
      "yerCommonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fsgame.proto.MSGBaseCommon.getDescriptor(),
        }, assigner);
    internal_static_Pro_PlayerCommon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pro_PlayerCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pro_PlayerCommon_descriptor,
        new java.lang.String[] { "Baseid", "Name", "Coor", "Hp", });
    com.fsgame.proto.MSGBaseCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
